chore(build) Improve CI (#76)
Add set -e so that we actually error out of build!

Added testing with real database (postgres).

Fix formatting in CHANGES

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -35,6 +35,9 @@ cache:
   - apt
   - pip
 
+services:
+  - postgresql
+
 env:
   - REQUIREMENTS=lowest
   - REQUIREMENTS=release
@@ -52,13 +55,16 @@ install:
 script:
   - python setup.py test
   - >
+    set -e;
     if [[ $TRAVIS_PYTHON_VERSION == 3.7 && $REQUIREMENTS == "release" ]]; then
+     # Test against a real DB (postgres)
+     python setup.py test --addopts --realdburl=postgres://postgres@localhost/;
      python setup.py build_sphinx compile_catalog;
-     echo "Running msgcheck"
+     echo "Running msgcheck";
      msgcheck -pwW flask_security/translations/*/LC_MESSAGES/flask_security.po;
      # run it again with spelling - but dont die on errors
-     echo "Running msgcheck with spell check (ignoring errors)"
-     (msgcheck -pwW -s str --pwl flask_security/translations/pwl.txt flask_security/translations/*/LC_MESSAGES/flask_security.po; exit 0);
+     echo "Running msgcheck with spell check (ignoring errors)";
+     msgcheck -pwW -s str --pwl flask_security/translations/pwl.txt flask_security/translations/*/LC_MESSAGES/flask_security.po || exit 0;
     fi
 
 after_script:
